Document: nettenance
Title: Debian nettenance Manual
Author: <insert document author here>
Abstract: This manual describes what nettenance is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nettenance/nettenance.sgml.gz

Format: postscript
Files: /usr/share/doc/nettenance/nettenance.ps.gz

Format: text
Files: /usr/share/doc/nettenance/nettenance.text.gz

Format: HTML
Index: /usr/share/doc/nettenance/html/index.html
Files: /usr/share/doc/nettenance/html/*.html
